sonar.projectKey=loginapp-aaa
sonar.organization=loginapp-team

sonar.sources=api/server.js
sonar.tests=api/tests
sonar.test.inclusions=api/tests/**/*.test.js

sonar.javascript.lcov.reportPaths=api/coverage/lcov.info
sonar.exclusions=api/node_modules/**,api/coverage/**
sonar.sourceEncoding=UTF-8
